name: Release iOS libs
on:
  push:
    branches:
      - master
    paths:
      - 'VERSIONS'
      - '.github/workflows/ios_libs.yml'
      - '.github/workflows/scripts/configure-ios.sh'
      - '.github/workflows/scripts/openssl-build-ios'
  pull_request:
    paths:
      - 'VERSIONS'
      - '.github/workflows/ios_libs.yml'
      - '.github/workflows/scripts/configure-ios.sh'
      - '.github/workflows/scripts/openssl-build-ios'

jobs:
  build:
    name: Build static libs for iOS
    runs-on: macos-latest
    strategy:
      matrix:
        archs: ['arm64', 'arm64e', 'x86_64']
    env:
      ARCH: ${{ matrix.archs }}
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Import lib versions in env
        run: cat VERSIONS >> $GITHUB_ENV

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: '12.2'

      - name: Build OpenSSL
        run: |
          # Setup build directory
          mkdir -p "build/openssl/$ARCH"
          cp -r .github/workflows/scripts/openssl-build-ios "build/openssl/$ARCH/src"
          cd "build/openssl/$ARCH/src"

          # Build OpenSSL
          if [[ "$ARCH" == 'arm64' || "$ARCH" == 'arm64e' ]]; then
              target="ios64-cross-$ARCH"
          elif [[ "$ARCH" == 'x86_64' ]]; then
              target="ios-sim-cross-x86_64"
          fi
          ./build-libssl.sh --targets="$target" --version="$OPENSSL_VERSION" --deprecated

          # Cleanup
          cd ..
          mv src/lib src/include .
          rm -rf src

      - name: Build Zlib
        run: |
          # Download Zlib
          wget "https://zlib.net/zlib-$ZLIB_VERSION.tar.gz" -O /tmp/zlib.tar.gz

          # Setup build directory
          mkdir -p "build/zlib/$ARCH/src"
          tar xvf /tmp/zlib.tar.gz -C "build/zlib/$ARCH/src" --strip-components=1
          cd "build/zlib/$ARCH/src"

          # Build Zlib
          CFLAGS='-O3' \
          CPPFLAGS='-O3' \
          ${{ github.workspace }}/.github/workflows/scripts/configure-ios.sh \
            "$ARCH" \
            --static \
            --prefix="${{ github.workspace }}/build/zlib/$ARCH"
          make -j$(sysctl hw.ncpu | awk '{print $2}') install

          # Cleanup
          cd ..
          rm -rf src

      - name: Build Libevent
        run: |
          # Download Libevent
          wget "https://github.com/libevent/libevent/releases/download/release-$LIBEVENT_VERSION/libevent-$LIBEVENT_VERSION.tar.gz" -O /tmp/libevent.tar.gz

          # Setup build directory
          mkdir -p "build/libevent/$ARCH/src"
          tar xvf /tmp/libevent.tar.gz -C "build/libevent/$ARCH/src" --strip-components=1
          cd "build/libevent/$ARCH/src"

          # Build Libevent
          if [[ "$ARCH" == 'arm64' ]]; then
              chost='aarch64-apple-darwin*'
          elif [[ "$ARCH" == 'arm64e' ]]; then
              chost='aarch64e-apple-darwin*'
          elif [[ "$ARCH" == 'x86_64' ]]; then
              chost='x86_64-apple-darwin*'
          fi
          CFLAGS="-O3 -I${{ github.workspace }}/build/openssl/$ARCH/include" \
          CPPFLAGS="-O3  -I${{ github.workspace }}/build/openssl/$ARCH/include" \
          LDFLAGS="-L${{ github.workspace }}/build/openssl/$ARCH/lib" \
          ${{ github.workspace }}/.github/workflows/scripts/configure-ios.sh \
            "$ARCH" \
            --disable-shared \
            --disable-samples \
            --enable-function-sections \
            --host="$chost" \
            --prefix="${{ github.workspace }}/build/libevent/$ARCH"
          make -j$(sysctl hw.ncpu | awk '{print $2}') install

          # Cleanup
          cd ..
          rm -rf src

      - name: Compress build directory
        if: ${{ github.event_name == 'push' && github.ref == 'master' }}
        run: tar -czvf "libs-$GITHUB_RUN_ID-$ARCH.tar.gz" build

      - name: Upload build archive
        if: ${{ github.event_name == 'push' && github.ref == 'master' }}
        uses: actions/upload-artifact@v2
        with:
          path: "libs-$GITHUB_RUN_ID-$ARCH.tar.gz"

  release:
    name: Release static libs for iOS
    needs: [build]
    if: ${{ github.event_name == 'push' && github.ref == 'master' }}
    runs-on: macos-latest
    steps:
      - name: Download arm64 build archive
        uses: actions/download-artifact@v2
        with:
          name: "libs-$GITHUB_RUN_ID-arm64.tar.gz"

      - name: Download arm64e build archive
        uses: actions/download-artifact@v2
        with:
          name: "libs-$GITHUB_RUN_ID-arm64e.tar.gz"

      - name: Download x86_64 build archive
        uses: actions/download-artifact@v2
        with:
          name: "libs-$GITHUB_RUN_ID-x86_64.tar.gz"

      - name: Decompress build archives
        run: tar -xvf "libs-$GITHUB_RUN_ID-*.tar.gz"

      - name: Display builds # TODO: REMOVE THIS
        run: ls -R build
